/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: abjonathan@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.InlineResponse2006
import io.swagger.client.model.InlineResponse2007
import io.swagger.client.model.InlineResponse2008
import io.swagger.client.model.Reservation
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object ReservationApi {

  /**
   * cancel reservation
   * 
   * Expected answers:
   *   code 200 : InlineResponse2008 (result)
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   * 
   * @param id 
   */
  def reservationCancelIdDelete(id: String)(implicit apiKey: ApiKeyValue): ApiRequest[InlineResponse2008] =
    ApiRequest[InlineResponse2008](ApiMethods.DELETE, "https://virtserver.swaggerhub.com/abjona/RocketInterplantetApi/1.0.0", "/reservation/cancel/{id}", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withPathParam("id", id)
      .withSuccessResponse[InlineResponse2008](200)
        /**
   * get reservation
   * 
   * Expected answers:
   *   code 200 : InlineResponse2007 (reservation)
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   */
  def reservationGetGet()(implicit apiKey: ApiKeyValue): ApiRequest[InlineResponse2007] =
    ApiRequest[InlineResponse2007](ApiMethods.GET, "https://virtserver.swaggerhub.com/abjona/RocketInterplantetApi/1.0.0", "/reservation/get", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withSuccessResponse[InlineResponse2007](200)
        /**
   * make reservation
   * 
   * Expected answers:
   *   code 200 : InlineResponse2006 (result)
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   * 
   * @param reservation 
   */
  def reservationMakeReservationPost(reservation: Option[Reservation] = None)(implicit apiKey: ApiKeyValue): ApiRequest[InlineResponse2006] =
    ApiRequest[InlineResponse2006](ApiMethods.POST, "https://virtserver.swaggerhub.com/abjona/RocketInterplantetApi/1.0.0", "/reservation/makeReservation", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withBody(reservation)
      .withSuccessResponse[InlineResponse2006](200)
      

}

