/**
 * Rocket Interplanet API
 * Rocket api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: abjonathan@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class CompanyInfo2 (
  idCompany: Option[String] = None,
  /* 0 to 5 */
  available: Option[Double] = None
) extends ApiModel


