/**
 * Rocket Interplanet API
 * Rocket api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: abjonathan@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class InlineResponse2008 (
  message: Option[String] = None,
  error: Option[Boolean] = None
) extends ApiModel


